### ISSUE TITLE
Camera rotating on body collision

### ISSUE THREAD

**Issue by TechSins** [BioLana/Survival-Game#1]
Weird Rotation issue when player collides with an object that has a RigidBody attached to it (Only Happens in first person) Doesn't seem to happen to any other objects as long as there is no RigidBody attached.

**Comment by nathanblair** [comment]
I don't recall anything but the player body having a rigidbody assigned to it. I know there were some mesh colliders assigned to various world objects but that's all I can think of. I will take a look at my version to check which bodies have rigidbodies applied though. Can you give any more background about whether this occurs on all four walls, the table, etc.? I assume we're running into this bug in the only testing environment we have right now, our Dev World?

**Comment by TechSins** [comment]
Walls are fine , only happens on the new gameObjects i have in the scene , which i have yet to push so you may pull it and try it out.

**Comment by nathanblair** [comment]
This bug has been squashed by fixing the player prefab Y rotation.
